### ISSUE TITLE
Block Details broken for blocks/chains with V1 Weight

### ISSUE THREAD

**Issue by MPM1107** [polkadot-js/apps#11040]
The Block Details tab in the explorer throws an error for chains still using V1Weight, and all chains if looking up an old block that still used V1. The error thrown is `v2Weight.proofSize.toBn is not a function`. I suspect this was caused by https://github.com/polkadot-js/apps/pull/10639, when a V1 Weight object is automatically converted to V2, the proofSize of the result gets set to BN_ZERO, which seems to not have a toBn method I assume? Not sure what the correct way to go about fixing this would be, so opening this issue instead of submitting a PR.

**Comment by TarikGul** [comment]
Can you provide a chain that is still using V1 so we can get this tested and fixed?

**Comment by MPM1107** [comment]
3DPass is one currently using it, first in the list for me under "Live networks". [Block details link](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.3dpscan.io#/explorer/query)

You can also test on other networks (like polkadot for example) by just going to a very old block that was still on v1, [example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.dotters.network#/explorer/query/1107)
